#!/bin/bash

WORKDIR=/sps
JAR=sps-rest-server.jar

CRED="\e[31m"
CGREEN="\e[32m"
CRESET="\e[0m"

start() {
  java -jar $WORKDIR/$JAR
}

stop() {
  kill `ps aux | pgrep -f $JAR`
}

status() {
  local pid=`ps aux | pgrep -f $JAR`

  if [[ ! -z "$pid" ]]; then
    local host=`netstat -lntp | grep $pid | awk -F ' ' '{ print $4 }'`
    echo -e "${CGREEN}●${CRESET} SPS Rest Server running\n  pid:  $pid\n  host: $host"
  else
    echo -e "${CRED}●${CRESET} SPS Rest Server is not running"
  fi
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
